development:
  <<: *defaults
  host: localhost
  database: doitidiot_development

test:
  <<: *defaults
  host: localhost
  database: doitidiot_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
